TP-GRUPO3/Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TP_GRUPO3.Context;
using TP_GRUPO3.Models;

namespace TP_GRUPO3.Controllers
{
    public class CarritoController : Controller
    {
        private readonly NegocioDatabaseContext _context;

        public CarritoController(NegocioDatabaseContext context)
        {
            _context = context;
        }

        // GET: Carrito
        public async Task<IActionResult> Index()
        {
            var negocioDatabaseContext = _context.Carrito.Include(c => c.producto).Include(c => c.usuario);
            return View(await negocioDatabaseContext.ToListAsync());
        }

        // GET: Carrito/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Carrito == null)
            {
                return NotFound();
            }

            var carrito = await _context.Carrito
                .Include(c => c.producto)
                .Include(c => c.usuario)
                .FirstOrDefaultAsync(m => m.id == id);
            if (carrito == null)
            {
                return NotFound();
            }

            return View(carrito);
        }

        // GET: Carrito/Create
        public IActionResult Create()
        {
            ViewData["productoid"] = new SelectList(_context.Productos, "id", "nombreColor");
            ViewData["usuarioid"] = new SelectList(_context.Usuario, "id", "nombreApellido");
            return View();
        }

        // POST: Carrito/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,productoid,usuarioid")] Carrito carrito)
        {
            if (!(ModelState.IsValid))
            {
                _context.Add(carrito);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["productoid"] = new SelectList(_context.Productos, "id", "nombreColor", carrito.productoid);
           
            ViewData["usuarioid"] = new SelectList(_context.Usuario, "id", "nombreApellido", carrito.usuarioid);
            return View(carrito);
        }

        // GET: Carrito/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Carrito == null)
            {
                return NotFound();
            }

            var carrito = await _context.Carrito.FindAsync(id);
            if (carrito == null)
            {
                return NotFound();
            }
            ViewData["productoid"] = new SelectList(_context.Productos, "id", "color", carrito.productoid);
            ViewData["usuarioid"] = new SelectList(_context.Usuario, "id", "apellido", carrito.usuarioid);
            return View(carrito);
        }

        // POST: Carrito/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,productoid,usuarioid")] Carrito carrito)
        {
            if (id != carrito.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(carrito);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarritoExists(carrito.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["productoid"] = new SelectList(_context.Productos, "id", "color", carrito.productoid);
            ViewData["usuarioid"] = new SelectList(_context.Usuario, "id", "apellido", carrito.usuarioid);
            return View(carrito);
        }

        // GET: Carrito/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Carrito == null)
            {
                return NotFound();
            }

            var carrito = await _context.Carrito
                .Include(c => c.producto)
                .Include(c => c.usuario)
                .FirstOrDefaultAsync(m => m.id == id);
            if (carrito == null)
            {
                return NotFound();
            }

            return View(carrito);
        }

        // POST: Carrito/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Carrito == null)
            {
                return Problem("Entity set 'NegocioDatabaseContext.Carrito'  is null.");
            }
            var carrito = await _context.Carrito.FindAsync(id);
            if (carrito != null)
            {
                _context.Carrito.Remove(carrito);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarritoExists(int id)
        {
          return (_context.Carrito?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

TP-GRUPO3/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TP_GRUPO3.Context;
using TP_GRUPO3.Models;

namespace TP_GRUPO3.Controllers
{
    public class ProductoController : Controller
    {
        private readonly NegocioDatabaseContext _context;

        public ProductoController(NegocioDatabaseContext context)
        {
            _context = context;
        }

        // GET: Producto
        public async Task<IActionResult> Index()
        {
              return _context.Productos != null ? 
                          View(await _context.Productos.ToListAsync()) :
                          Problem("Entity set 'NegocioDatabaseContext.Productos'  is null.");
        }

        // GET: Producto/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Productos == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .FirstOrDefaultAsync(m => m.id == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // GET: Producto/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Producto/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,nombre,color,precio,cantidad,talle")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(producto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(producto);
        }

        // GET: Producto/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Productos == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
            return View(producto);
        }

        // POST: Producto/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nombre,color,precio,cantidad,talle")] Producto producto)
        {
            if (id != producto.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(producto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoExists(producto.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(producto);
        }

        // GET: Producto/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Productos == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .FirstOrDefaultAsync(m => m.id == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // POST: Producto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Productos == null)
            {
                return Problem("Entity set 'NegocioDatabaseContext.Productos'  is null.");
            }
            var producto = await _context.Productos.FindAsync(id);
            if (producto != null)
            {
                _context.Productos.Remove(producto);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductoExists(int id)
        {
          return (_context.Productos?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

TP-GRUPO3/Controllers/SesionController.cs
using Microsoft.AspNetCore.Mvc;
using TP_GRUPO3.Context;
using TP_GRUPO3.Models;
using TP_GRUPO3.Utils;

namespace TP_GRUPO3.Controllers
{
    public class SesionController : Controller
    {
        private readonly NegocioDatabaseContext _context;

        public SesionController(NegocioDatabaseContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            // Si las variables de sesión ya están asignadas, redirige al dashboard
            if (HttpContext.Session.GetString("Username") != null)
            {                
                return RedirectToAction("Index","Home");
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public IActionResult Login(string username, string password)
        {
            // Si ya hay variables de usuario porque ya nos logeamos, no debería ir al login
            if (HttpContext.Session.GetString("Username") != null)
            {                
                return RedirectToAction("Index", "Home");
            }

            // Validar el usuario y contraseña en la base de datos
            var user = _context.Usuario.FirstOrDefault(u => u.Username == username && u.Password == password);

            if (user != null)
            {             
                HttpContext.Session.SetString("Username", user.Username.ToString());

                HttpContext.Session.SetObject("Usuario", user);

                ViewData["Usuario"] = user;                
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["LoginError"] = "Credenciales inválidas";
                Usuario invalidUser = new Usuario { nombre = username };
                return RedirectToAction(nameof(Index));
            }
        }

        public IActionResult Logout()
        {
            // Eliminar las variables de sesión
            HttpContext.Session.Remove("Username");
            HttpContext.Session.Remove("Usuario");

            return RedirectToAction("Index", "Home"); // Redirigir a la página de inicio u otra página de tu elección
        }

        // GET: Sessions/CrearUsuario
        public IActionResult CrearUsuario()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Usuario usuario)
        {
            if (ModelState.IsValid && (!UsernameExists(usuario.Username)))
            {

                _context.Add(usuario);
                await _context.SaveChangesAsync();
                
                HttpContext.Session.SetString("Username", usuario.Username.ToString());
                // Guardar el objeto usuario en la sesión
                HttpContext.Session.SetObject("Usuario", usuario);
                
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["CreateNewUserError"] = "No se pudo crear el usuario debido a duplicados. Usuario y/o dni ya existentes.";                
                return RedirectToAction("CrearUsuario");
            }

        }


        private bool UsernameExists(string user)
        {
            bool exists = _context.Usuario.Any(e => e.Username == user);
            if (exists)
            {
                TempData["CrearUsuario"] = "Usuario repetido.";
            }
            return exists;
        }
    }
}

TP-GRUPO3/Views/Shared/_Layout.cshtml
@{
    var usuario = Context.Items["Usuario"] as Usuario;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ORTumentaria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow mb-3">
            <div class="container-fluid" id="nav">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color:floralwhite">Inicio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (usuario != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Producto" asp-action="Index" style="color:floralwhite" id="prodNav">Producto</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Usuario" asp-action="Index" style="color:floralwhite" id="usuarioNav">Usuario</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Carrito" asp-action="Index" style="color:floralwhite" id="carritoNav">Carrito</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy" style="color:floralwhite" id="privNav">Privacidad</a>
                            </li>                   
                            <li class="nav-item">
                                <form asp-controller="Sesion" asp-action="Logout" method="post">
                                    <button type="submit" class="btn botonVerde btn-secondary ">Cerrar sesión</button>
                                </form>
                            </li>
                        }

                        else{
                            <li class="nav-item">
                                <a asp-area="" asp-controller="Sesion" asp-action="Index">Iniciar sesión</a>
                            </li>
                        }
                        
                        

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TP_GRUPO3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src ="~/js/cambioNav.js"> </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>